number = str(input('Digite um número: '))
n1 = (number[0])
n2 = (number[1])
n3 = (number[2])
n4 = (number[3])
print(f'Unidade: {n1}')
print(f'Dezena: {n2}')
print(f'Centena: {n3}')
print(f'Milhar: {n4}')
