name = str(input('Digite o seu nome completo: '))
print(name.upper())
print(name.lower())
name2 = (name.strip())
name3 = (name2.replace(' ',''))
name4 = (name.split())
name5 = (len(name4[0]))
print(len(name3))
print(name5)
